{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hypersdk.fullname" . }}-data
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
---
{{- end }}
{{- if and .Values.persistence.exports.enabled (not .Values.persistence.exports.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hypersdk.fullname" . }}-exports
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
  {{- with .Values.persistence.exports.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.exports.accessMode }}
  {{- if .Values.persistence.exports.storageClass }}
  storageClassName: {{ .Values.persistence.exports.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.exports.size | quote }}
{{- end }}
