{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hypersdk.fullname" . }}
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hypersdk.fullname" . }}
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hypersdk.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hypersdk.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
