{{- if and .Values.route.enabled (not .Values.ingress.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "hypersdk.fullname" . }}
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  {{- if .Values.route.path }}
  path: {{ .Values.route.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "hypersdk.fullname" . }}
    weight: 100
  port:
    targetPort: http
  {{- if .Values.route.tls }}
  tls:
    {{- if .Values.route.tls.termination }}
    termination: {{ .Values.route.tls.termination }}
    {{- end }}
    {{- if .Values.route.tls.insecureEdgeTerminationPolicy }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    {{- end }}
    {{- if .Values.route.tls.certificate }}
    certificate: {{ .Values.route.tls.certificate }}
    {{- end }}
    {{- if .Values.route.tls.key }}
    key: {{ .Values.route.tls.key }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: {{ .Values.route.tls.caCertificate }}
    {{- end }}
    {{- if .Values.route.tls.destinationCACertificate }}
    destinationCACertificate: {{ .Values.route.tls.destinationCACertificate }}
    {{- end }}
  {{- end }}
  {{- if .Values.route.wildcardPolicy }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
  {{- end }}
{{- end }}
