apiVersion: v1
kind: Service
metadata:
  name: {{ include "hypersdk.fullname" . }}
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "hypersdk.selectorLabels" . | nindent 4 }}
---
{{- if .Values.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hypersdk.fullname" . }}-external
  labels:
    {{- include "hypersdk.labels" . | nindent 4 }}
  {{- with .Values.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - port: {{ .Values.externalService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hypersdk.selectorLabels" . | nindent 4 }}
{{- end }}
