apiVersion: v1
kind: ServiceAccount
metadata:
  name: hypervisord
  namespace: hypersdk
  labels:
    app: hypervisord
    app.kubernetes.io/name: hypervisord
    app.kubernetes.io/component: serviceaccount
    app.kubernetes.io/part-of: hypersdk
automountServiceAccountToken: true

# Optional: Image pull secrets if using private registry
# imagePullSecrets:
# - name: regcred
